###########
# site.url, site.title

url:   'http://planetruby.github.io/gems'
title: 'Planet Ruby'


########
# more settings

## markdown: redcarpet
markdown: kramdown


sass:
  sass_dir: css
  style:    expanded


exclude:
- README.md


safe: true
lsi: false

