
## note: use title same as heading 1 in readme
##   needed for primer (default) theme to avoid duplicate title (if missing gets auto-added)

title: "Best of Ruby Gems Series"



titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
## see   https://github.com/benbalter/jekyll-titles-from-headings


plugins:
- jekyll-titles-from-headings
- jekyll-avatar
- jemoji
